version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.33
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-23-21-156-171.compute-1.amazonaws.com
            database: d3c5la7p3aako8
            schema: public
            user: idumqpvkiymjhv
            password: f0e0d6bc88acb0442a975043423e8642fbac09336f4266e4862a31b06c942ddb
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true